<?xml version="1.0"?>

<!-- This macro adds a convenient TF frame at the tip of the closed gripper. -->
<!-- The position of the TF frame has not been measured at all and needs to be calibrated. -->

<robot name="robotiq_85_gripper_o2ac" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- This seems too long when measuring the sensor,
       but works out when calibrating the tip_link to the world. -->
  <xacro:property name="ft300_length" value="0.0525"/>

  <xacro:macro name="robotiq_85_gripper_with_ft300" params="prefix parent">
    <!-- Add the force sensor in front of the gripper. -->
    <joint name="${prefix}ft300_joint" type="fixed">
      <parent link="${parent}"/>
      <child link="${prefix}ft300_link"/>
      <origin rpy="0.0 ${pi/2} 0.0" xyz="${ft300_length/2} 0.0 0.0"/>
    </joint>
    <link name="${prefix}ft300_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder length="${ft300_length}" radius="0.0375"/>
        </geometry>
        <material name="Black">
          <color rgba="0.1 0.1 0.1 1.0"/>
        </material>
      </visual>
    </link>

    <xacro:include filename="$(find robotiq_description)/urdf/robotiq_85_gripper.urdf.xacro" />
    
    <xacro:robotiq_85_gripper prefix="${prefix}" parent="${parent}">
        <origin rpy="0.0 0.0 0.0" xyz="${ft300_length} 0.0 0.0"/>
    </xacro:robotiq_85_gripper>

    <!-- Add additional links for us to plan with. Oriented like the UR frame. -->
    <joint name="${prefix}robotiq_85_tip_link_joint" type="fixed">
      <parent link="${prefix}robotiq_85_base_link"/>
      <child link="${prefix}robotiq_85_tip_link"/>
      <origin rpy="0.0 0.0 0.0" xyz=".163 0.0 0.0"/>
    </joint>
    <link name="${prefix}robotiq_85_tip_link"/>

  </xacro:macro>
</robot>
