# Define the goal
# Fields that have to be set:
string object_name  # Name of the object to place
geometry_msgs/PoseStamped object_target_pose  # The target pose that the object will be placed at

# Optional fields: (If not set, the default values will be used. See README for more details)
bool release_object_after_place  # If set to True the plan includes the robot retreating after placing the object
string object_subframe_to_place  # If defined, the target pose will be set for this subframe instead of the object's frame. Us the form: "object_name/subframe_name"
string approach_place_direction_reference_frame  # The coordinate frame in which the direction of placing the object (approach_place_direction) is defined
float64[] approach_place_direction  # Vector of the form [x,y,z] for setting the direction of placing the object
string robot_name  # Name of the robot holding the object

# Fields currently not in use (these have no effect yet)
float64 approach_place_min_dist  # Minimum approach distance in the approach_place_direction when placing the object
float64 approach_place_max_dist  # Maximum approach distance in the approach_place_direction when placing the object
float64 retreat_min_dist  # Minimum lift distance in the retreat direction
float64 retreat_max_dist  # Maximum lift distance in the retreat direction
string surface_link  # name of link on which the object lies before picking
---
# Define the result
bool success
moveit_task_constructor_msgs/Solution solution
---
# Define a feedback message
