# This action takes charge of the robots and 

# Request
string pulley_id   # Which pulley to turn. "motor_pulley", "large_pulley"
string camera_id   # Which camera is looking at the pulley

---
# Result (returned from the server to the client)

bool succeeded

---
# Feedback (values that can be sent to the client while the action is running)
