# This action will be called when a tool is being held close to a target hole.
# It should return the distance from the tooltip to the target,
# for the robot to adjust its position.
# The important part is the x-y offset relative to the tooltip.

# Request
geometry_msgs/PointStamped expected_tooltip_point
geometry_msgs/PointStamped expected_hole_point
string camera_id   # Which camera to use. "a_bot_cam_outside", "a_bot_cam_inside"...

---
# Result (returned from the server to the client)

bool succeeded
float32 confidence
geometry_msgs/PointStamped detected_hole_point
geometry_msgs/Point tooltip_hole_offset   # The vector from tooltip to hole center

---
# Feedback (values that can be sent to the client while the action is running)

