# This action picks a screw.

geometry_msgs/PoseStamped screw_pose # This is set at the very tip of the head, 
                                    # with the x-axis pointing into the head.

float64 z_axis_rotation             # If this is set, the orientation of the item_pose is ignored and set facing downward, rotated by this.

string robot_name                   # "a_bot", "b_bot", "c_bot"
string tool_name                    # "outer_gripper", "inner_gripper", "suction", "screw_tool" or empty

uint8 screw_size                    # M3, M4, M6 (without the M)
---
# success
bool success
---
# Feedback
float32 progress 
