# Only one command can be set at a time. 
bool stop
bool setScrew_fasten
bool peg_fasten
bool big_nut_fasten
bool small_nut_fasten

---
# Define the result
bool success

---
# Define a feedback message
uint32 motor_speed
uint32 countTime
