uint8 observation_type
TouchObservation touch_observation
LookObservation look_observation
PlaceObservation place_observation
geometry_msgs/PoseWithCovariance distribution

uint8 TOUCH_OBSERVATION = 0
uint8 LOOK_OBSERVATION = 1
uint8 PLACE_OBSERVATION = 2
---
bool success
geometry_msgs/PoseWithCovariance distribution
---