#!/bin/bash

################################################################################

# Allow current host user to access files generated by Docker 'root' user.
chown -R ${HOST_UID}:${HOST_GID} /root/share/
chown -R ${HOST_UID}:${HOST_GID} /root/.ros/
chown -R ${HOST_UID}:${HOST_GID} /root/o2ac-ur/catkin_ws/
chown -R ${HOST_UID}:${HOST_GID} /root/o2ac-ur/underlay_ws/
chown -R ${HOST_UID}:${HOST_GID} /root/o2ac-ur/docker/
